//******************************************************
//Instituto Federal de São Paulo - Campus Sertãozinho
//Disciplina......: M3LPBD
//Programação de Computadores e Dispositivos Móveis
//Aluno...........: Wesley AV
//******************************************************

package meu_projeto_final;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wesley
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        carregarTabela();//chama o método que carrega os dados da tabela (se houverem)
        carregarCombo();//chama o método que carrega os dados do combobox (se houverem)

    }
    

    private void carregarTabela() {
        try {
            Connection con = ConexaoMySQL.getConexaoMySQL();//conexão utilizando a classe ConexaoMySQL
            
            String cmd = "select * from disciplina";//string que recebe o resultado do select no banco
            
            ResultSet res = con.createStatement().executeQuery(cmd);//resultado do select armazenado no variável res
            
            while (res.next()) {//laço de repetição que pega os campos digitados
                String nomeDB = res.getString("nome");
                int idDB = res.getInt("id");
                int carga_horariaDB = res.getInt("carga_horaria");
                String cursoDB = res.getString("curso");
                int numero_vagasDB = res.getInt("numero_vagas");
                String periodoDB = res.getString("periodo");

                Vector v = new Vector();//vetor que armazena os dados

                v.add(idDB);
                v.add(nomeDB);
                v.add(carga_horariaDB);
                v.add(cursoDB);
                v.add(numero_vagasDB);
                v.add(periodoDB);

                ((DefaultTableModel) jTable1.getModel()).addRow(v);//pega os dados da tabela e adiciona em uma linha
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void carregarCombo() {
        //ResultSet res = null;
        try {
            Connection con = ConexaoMySQL.getConexaoMySQL();
            String cmd = "select nome from disciplina";
            ResultSet res = con.createStatement().executeQuery(cmd);
            while (res.next()) {
                String nomeDB = res.getString("nome");//atribui o nome da disciplina que veio do select no banco

                ((DefaultComboBoxModel) jComboBox1.getModel()).addElement(nomeDB);

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    //método que limpa os campos de texto após a mensagem de dados inseridos
    public void acaobotaolimpa() {
        jTextField1_nome.setText("");
        jTextField2_carga_horaria.setText("");
        jTextField3_curso.setText("");
        jTextField4_numero_vagas.setText("");
        jTextField5_periodo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_nome = new javax.swing.JLabel();
        jLabel2_carga_horaria = new javax.swing.JLabel();
        jTextField1_nome = new javax.swing.JTextField();
        jTextField2_carga_horaria = new javax.swing.JTextField();
        jLabel3_curso = new javax.swing.JLabel();
        jTextField3_curso = new javax.swing.JTextField();
        jLabel4_numero_vagas = new javax.swing.JLabel();
        jTextField4_numero_vagas = new javax.swing.JTextField();
        jLabel5_periodo = new javax.swing.JLabel();
        jTextField5_periodo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1_cadastrar = new javax.swing.JButton();
        jButton2_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton3_apgar = new javax.swing.JButton();
        jButton1_atualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1_nome.setText("Disciplina");

        jLabel2_carga_horaria.setText("Carga Horária");

        jTextField1_nome.setToolTipText("Informe o nome da disciplina");
        jTextField1_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_nomeActionPerformed(evt);
            }
        });
        jTextField1_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1_nomeKeyTyped(evt);
            }
        });

        jTextField2_carga_horaria.setToolTipText("Informe a carga horária");
        jTextField2_carga_horaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_carga_horariaActionPerformed(evt);
            }
        });

        jLabel3_curso.setText("Curso");

        jTextField3_curso.setToolTipText("Informe o curso");
        jTextField3_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_cursoActionPerformed(evt);
            }
        });

        jLabel4_numero_vagas.setText("Nº de Vagas");

        jTextField4_numero_vagas.setToolTipText("Informe o número de vagas");

        jLabel5_periodo.setText("Período");

        jTextField5_periodo.setToolTipText("Informe o período");
        jTextField5_periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5_periodoActionPerformed(evt);
            }
        });

        jButton1_cadastrar.setText("CADASTRAR");
        jButton1_cadastrar.setToolTipText("Envie os dados");
        jButton1_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_cadastrarActionPerformed(evt);
            }
        });

        jButton2_cancelar.setText("SAIR");
        jButton2_cancelar.setToolTipText("Sair do sistema");
        jButton2_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_cancelarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Disciplina", "Carga Horária", "Curso", "Nº de Vagas", "Período"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("TABELA GERAL");

        jComboBox1.setToolTipText("Para excluir selecione uma disciplina");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setText("EXCLUIR DISCIPLINAS");

        jButton3_apgar.setText("Excluir Dados");
        jButton3_apgar.setToolTipText("Exclua os dados da disciplina escolhida");
        jButton3_apgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_apgarActionPerformed(evt);
            }
        });

        jButton1_atualizar.setText("ATUALIZAR TELA");
        jButton1_atualizar.setToolTipText("Atualize todas as informações");
        jButton1_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3_curso)
                                    .addComponent(jLabel1_nome)
                                    .addComponent(jLabel5_periodo))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_nome)
                                    .addComponent(jTextField3_curso)
                                    .addComponent(jTextField5_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2_carga_horaria)
                                    .addComponent(jLabel4_numero_vagas, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4_numero_vagas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2_carga_horaria, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_cadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1_atualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2_cancelar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3_apgar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_nome)
                    .addComponent(jTextField1_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_carga_horaria)
                    .addComponent(jTextField2_carga_horaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_curso)
                    .addComponent(jTextField3_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4_numero_vagas)
                    .addComponent(jTextField4_numero_vagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5_periodo)
                    .addComponent(jTextField5_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_cadastrar)
                    .addComponent(jButton2_cancelar)
                    .addComponent(jButton1_atualizar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3_apgar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(693, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5_periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5_periodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_periodoActionPerformed

    private void jButton1_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_cadastrarActionPerformed
        try {//aqui verifico se todos os campos estão vazios, caso estejam, solicito que sejam preenchidos
            if (jTextField1_nome.getText().isEmpty()
                    || jTextField2_carga_horaria.getText().isEmpty()
                    || jTextField3_curso.getText().isEmpty()
                    || jTextField4_numero_vagas.getText().isEmpty()
                    || jTextField5_periodo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Ops! Preencha todos os campos!", "AVISO!", JOptionPane.ERROR_MESSAGE);
            } else {
                //insert dos dados no banco
                String cmd = "insert into disciplina (nome, carga_horaria, curso, numero_vagas, periodo) VALUES " + "('"
                        + jTextField1_nome.getText() + "', " + ""
                        + jTextField2_carga_horaria.getText() + ", '"
                        + jTextField3_curso.getText() + "', "
                        + jTextField4_numero_vagas.getText() + ", '"
                        + jTextField5_periodo.getText() + "')";

                String mensagem = "Dados inseridos com sucesso!"; //exibindo mensagem de confirmação de dados inseridos no bd
                JOptionPane.showMessageDialog(rootPane, mensagem, "AVISO!", JOptionPane.INFORMATION_MESSAGE);
                //chama o metodo que limpa todos os campos de texto logo após o cadastro
                acaobotaolimpa();
                
                Connection con = ConexaoMySQL.getConexaoMySQL();
                //String cmd = null;
                con.createStatement().executeUpdate(cmd);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1_cadastrarActionPerformed

    private void jTextField3_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_cursoActionPerformed

    private void jButton2_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_cancelarActionPerformed
        
        
        //questiona o usuário ao sair
        JOptionPane sair = new JOptionPane();
        int Sair = sair.showConfirmDialog(null, "Tem certeza que deseja SAIR?", "Sair", JOptionPane.YES_NO_OPTION);
        if (Sair == JOptionPane.YES_OPTION) {
            //    System.exit(0);
            this.dispose();

        } else {
            if (Sair == JOptionPane.NO_OPTION) {

            }
        }


    }//GEN-LAST:event_jButton2_cancelarActionPerformed

    private void jTextField1_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_nomeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3_apgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_apgarActionPerformed

        JOptionPane excluir = new JOptionPane();//questiona o usuário ao excluir a disciplina
        int Excluir = excluir.showConfirmDialog(null, "Todos os dados desta disciplina serão perdidos, deseja excluir?", "Sair", JOptionPane.YES_NO_OPTION);
        if (Excluir == JOptionPane.YES_OPTION) {
            try {
                String cmd = "delete from disciplina where nome = '" + jComboBox1.getSelectedItem() + "'";//delete no banco

                String mensagem = "Dados removidos com sucesso!"; //exibindo mensagem de confirmação de dados removidos no bd
                JOptionPane.showMessageDialog(rootPane, mensagem, "AVISO!", JOptionPane.INFORMATION_MESSAGE);
                
                String mensagem2 = "Atualize a TELA!"; //exibindo mensagem de confirmação de dados removidos no bd
                JOptionPane.showMessageDialog(rootPane, mensagem2, "AVISO!", JOptionPane.INFORMATION_MESSAGE);
                

                Connection con = ConexaoMySQL.getConexaoMySQL();
                con.createStatement().executeUpdate(cmd);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        } else {
            if (Excluir == JOptionPane.NO_OPTION) {
                //this.dispose();
            }
        }
    }//GEN-LAST:event_jButton3_apgarActionPerformed

    private void jButton1_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_atualizarActionPerformed
        //refresh na tela
        this.dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_jButton1_atualizarActionPerformed

    private void jTextField1_nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_nomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_nomeKeyTyped

    private void jTextField2_carga_horariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_carga_horariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_carga_horariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_atualizar;
    private javax.swing.JButton jButton1_cadastrar;
    private javax.swing.JButton jButton2_cancelar;
    private javax.swing.JButton jButton3_apgar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1_nome;
    private javax.swing.JLabel jLabel2_carga_horaria;
    private javax.swing.JLabel jLabel3_curso;
    private javax.swing.JLabel jLabel4_numero_vagas;
    private javax.swing.JLabel jLabel5_periodo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_nome;
    private javax.swing.JTextField jTextField2_carga_horaria;
    private javax.swing.JTextField jTextField3_curso;
    private javax.swing.JTextField jTextField4_numero_vagas;
    private javax.swing.JTextField jTextField5_periodo;
    // End of variables declaration//GEN-END:variables
}
